// <auto-generated />
using System;
using Gaby.io.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace gaby.io.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260806193038_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gaby.io.Models.AuthorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("integer");

                    b.Property<char>("Gender")
                        .HasColumnType("char(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("Name");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Gaby.io.Models.BookGenreModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("BookId", "GenreId")
                        .IsUnique();

                    b.ToTable("BookGenres");
                });

            modelBuilder.Entity("Gaby.io.Models.BookModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<int>("PageCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PublisherId");

                    b.HasIndex("Title", "AuthorId")
                        .IsUnique();

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Gaby.io.Models.CountryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "AFG",
                            Name = "Afeganistão"
                        },
                        new
                        {
                            Id = 2,
                            Code = "ZAF",
                            Name = "África do Sul"
                        },
                        new
                        {
                            Id = 3,
                            Code = "ALB",
                            Name = "Albânia"
                        },
                        new
                        {
                            Id = 4,
                            Code = "DEU",
                            Name = "Alemanha"
                        },
                        new
                        {
                            Id = 5,
                            Code = "AND",
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 6,
                            Code = "AGO",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 7,
                            Code = "ATG",
                            Name = "Antígua e Barbuda"
                        },
                        new
                        {
                            Id = 8,
                            Code = "SAU",
                            Name = "Arábia Saudita"
                        },
                        new
                        {
                            Id = 9,
                            Code = "DZA",
                            Name = "Argélia"
                        },
                        new
                        {
                            Id = 10,
                            Code = "ARG",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 11,
                            Code = "ARM",
                            Name = "Armênia"
                        },
                        new
                        {
                            Id = 12,
                            Code = "AUS",
                            Name = "Austrália"
                        },
                        new
                        {
                            Id = 13,
                            Code = "AUT",
                            Name = "Áustria"
                        },
                        new
                        {
                            Id = 14,
                            Code = "AZE",
                            Name = "Azerbaijão"
                        },
                        new
                        {
                            Id = 15,
                            Code = "BHS",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 16,
                            Code = "BGD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 17,
                            Code = "BRB",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 18,
                            Code = "BHR",
                            Name = "Barém"
                        },
                        new
                        {
                            Id = 19,
                            Code = "BEL",
                            Name = "Bélgica"
                        },
                        new
                        {
                            Id = 20,
                            Code = "BLZ",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 21,
                            Code = "BEN",
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 22,
                            Code = "BLR",
                            Name = "Bielorrússia"
                        },
                        new
                        {
                            Id = 23,
                            Code = "BOL",
                            Name = "Bolívia"
                        },
                        new
                        {
                            Id = 24,
                            Code = "BIH",
                            Name = "Bósnia e Herzegovina"
                        },
                        new
                        {
                            Id = 25,
                            Code = "BWA",
                            Name = "Botsuana"
                        },
                        new
                        {
                            Id = 26,
                            Code = "BRA",
                            Name = "Brasil"
                        },
                        new
                        {
                            Id = 27,
                            Code = "BRN",
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 28,
                            Code = "BGR",
                            Name = "Bulgária"
                        },
                        new
                        {
                            Id = 29,
                            Code = "BFA",
                            Name = "Burquina Faso"
                        },
                        new
                        {
                            Id = 30,
                            Code = "BDI",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 31,
                            Code = "BTN",
                            Name = "Butão"
                        },
                        new
                        {
                            Id = 32,
                            Code = "CPV",
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = 33,
                            Code = "CMR",
                            Name = "Camarões"
                        },
                        new
                        {
                            Id = 34,
                            Code = "KHM",
                            Name = "Camboja"
                        },
                        new
                        {
                            Id = 35,
                            Code = "CAN",
                            Name = "Canadá"
                        },
                        new
                        {
                            Id = 36,
                            Code = "QAT",
                            Name = "Catar"
                        },
                        new
                        {
                            Id = 37,
                            Code = "KAZ",
                            Name = "Cazaquistão"
                        },
                        new
                        {
                            Id = 38,
                            Code = "TCD",
                            Name = "Chade"
                        },
                        new
                        {
                            Id = 39,
                            Code = "CHL",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 40,
                            Code = "CHN",
                            Name = "China"
                        },
                        new
                        {
                            Id = 41,
                            Code = "CYP",
                            Name = "Chipre"
                        },
                        new
                        {
                            Id = 42,
                            Code = "COL",
                            Name = "Colômbia"
                        },
                        new
                        {
                            Id = 43,
                            Code = "COM",
                            Name = "Comores"
                        },
                        new
                        {
                            Id = 44,
                            Code = "COG",
                            Name = "Congo"
                        },
                        new
                        {
                            Id = 45,
                            Code = "PRK",
                            Name = "Coreia do Norte"
                        },
                        new
                        {
                            Id = 46,
                            Code = "KOR",
                            Name = "Coreia do Sul"
                        },
                        new
                        {
                            Id = 47,
                            Code = "CIV",
                            Name = "Costa do Marfim"
                        },
                        new
                        {
                            Id = 48,
                            Code = "CRI",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 49,
                            Code = "HRV",
                            Name = "Croácia"
                        },
                        new
                        {
                            Id = 50,
                            Code = "CUB",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 51,
                            Code = "DNK",
                            Name = "Dinamarca"
                        },
                        new
                        {
                            Id = 52,
                            Code = "DJI",
                            Name = "Djibuti"
                        },
                        new
                        {
                            Id = 53,
                            Code = "DMA",
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 54,
                            Code = "EGY",
                            Name = "Egito"
                        },
                        new
                        {
                            Id = 55,
                            Code = "SLV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 56,
                            Code = "ARE",
                            Name = "Emirados Árabes Unidos"
                        },
                        new
                        {
                            Id = 57,
                            Code = "ECU",
                            Name = "Equador"
                        },
                        new
                        {
                            Id = 58,
                            Code = "ERI",
                            Name = "Eritreia"
                        },
                        new
                        {
                            Id = 59,
                            Code = "SVK",
                            Name = "Eslováquia"
                        },
                        new
                        {
                            Id = 60,
                            Code = "SVN",
                            Name = "Eslovênia"
                        },
                        new
                        {
                            Id = 61,
                            Code = "ESP",
                            Name = "Espanha"
                        },
                        new
                        {
                            Id = 62,
                            Code = "USA",
                            Name = "Estados Unidos"
                        },
                        new
                        {
                            Id = 63,
                            Code = "EST",
                            Name = "Estônia"
                        },
                        new
                        {
                            Id = 64,
                            Code = "SWZ",
                            Name = "Eswatini"
                        },
                        new
                        {
                            Id = 65,
                            Code = "ETH",
                            Name = "Etiópia"
                        },
                        new
                        {
                            Id = 66,
                            Code = "FJI",
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 67,
                            Code = "PHL",
                            Name = "Filipinas"
                        },
                        new
                        {
                            Id = 68,
                            Code = "FIN",
                            Name = "Finlândia"
                        },
                        new
                        {
                            Id = 69,
                            Code = "FRA",
                            Name = "França"
                        },
                        new
                        {
                            Id = 70,
                            Code = "GAB",
                            Name = "Gabão"
                        },
                        new
                        {
                            Id = 71,
                            Code = "GMB",
                            Name = "Gâmbia"
                        },
                        new
                        {
                            Id = 72,
                            Code = "GHA",
                            Name = "Gana"
                        },
                        new
                        {
                            Id = 73,
                            Code = "GEO",
                            Name = "Geórgia"
                        },
                        new
                        {
                            Id = 74,
                            Code = "GRD",
                            Name = "Granada"
                        },
                        new
                        {
                            Id = 75,
                            Code = "GRC",
                            Name = "Grécia"
                        },
                        new
                        {
                            Id = 76,
                            Code = "GTM",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 77,
                            Code = "GUY",
                            Name = "Guiana"
                        },
                        new
                        {
                            Id = 78,
                            Code = "GIN",
                            Name = "Guiné"
                        },
                        new
                        {
                            Id = 79,
                            Code = "GNQ",
                            Name = "Guiné Equatorial"
                        },
                        new
                        {
                            Id = 80,
                            Code = "GNB",
                            Name = "Guiné-Bissau"
                        },
                        new
                        {
                            Id = 81,
                            Code = "HTI",
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 82,
                            Code = "HND",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 83,
                            Code = "HUN",
                            Name = "Hungria"
                        },
                        new
                        {
                            Id = 84,
                            Code = "YEM",
                            Name = "Iêmen"
                        },
                        new
                        {
                            Id = 85,
                            Code = "MHL",
                            Name = "Ilhas Marshall"
                        },
                        new
                        {
                            Id = 86,
                            Code = "SLB",
                            Name = "Ilhas Salomão"
                        },
                        new
                        {
                            Id = 87,
                            Code = "IND",
                            Name = "Índia"
                        },
                        new
                        {
                            Id = 88,
                            Code = "IDN",
                            Name = "Indonésia"
                        },
                        new
                        {
                            Id = 89,
                            Code = "IRN",
                            Name = "Irã"
                        },
                        new
                        {
                            Id = 90,
                            Code = "IRQ",
                            Name = "Iraque"
                        },
                        new
                        {
                            Id = 91,
                            Code = "IRL",
                            Name = "Irlanda"
                        },
                        new
                        {
                            Id = 92,
                            Code = "ISL",
                            Name = "Islândia"
                        },
                        new
                        {
                            Id = 93,
                            Code = "ISR",
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 94,
                            Code = "ITA",
                            Name = "Itália"
                        },
                        new
                        {
                            Id = 95,
                            Code = "JAM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 96,
                            Code = "JPN",
                            Name = "Japão"
                        },
                        new
                        {
                            Id = 97,
                            Code = "JOR",
                            Name = "Jordânia"
                        },
                        new
                        {
                            Id = 98,
                            Code = "KIR",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 99,
                            Code = "KWT",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 100,
                            Code = "LAO",
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 101,
                            Code = "LSO",
                            Name = "Lesoto"
                        },
                        new
                        {
                            Id = 102,
                            Code = "LVA",
                            Name = "Letônia"
                        },
                        new
                        {
                            Id = 103,
                            Code = "LBN",
                            Name = "Líbano"
                        },
                        new
                        {
                            Id = 104,
                            Code = "LBR",
                            Name = "Libéria"
                        },
                        new
                        {
                            Id = 105,
                            Code = "LBY",
                            Name = "Líbia"
                        },
                        new
                        {
                            Id = 106,
                            Code = "LIE",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 107,
                            Code = "LTU",
                            Name = "Lituânia"
                        },
                        new
                        {
                            Id = 108,
                            Code = "LUX",
                            Name = "Luxemburgo"
                        },
                        new
                        {
                            Id = 109,
                            Code = "MDG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 110,
                            Code = "MYS",
                            Name = "Malásia"
                        },
                        new
                        {
                            Id = 111,
                            Code = "MWI",
                            Name = "Malauí"
                        },
                        new
                        {
                            Id = 112,
                            Code = "MDV",
                            Name = "Maldivas"
                        },
                        new
                        {
                            Id = 113,
                            Code = "MLI",
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 114,
                            Code = "MLT",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 115,
                            Code = "MAR",
                            Name = "Marrocos"
                        },
                        new
                        {
                            Id = 116,
                            Code = "MUS",
                            Name = "Maurício"
                        },
                        new
                        {
                            Id = 117,
                            Code = "MRT",
                            Name = "Mauritânia"
                        },
                        new
                        {
                            Id = 118,
                            Code = "MEX",
                            Name = "México"
                        },
                        new
                        {
                            Id = 119,
                            Code = "FSM",
                            Name = "Micronésia"
                        },
                        new
                        {
                            Id = 120,
                            Code = "MOZ",
                            Name = "Moçambique"
                        },
                        new
                        {
                            Id = 121,
                            Code = "MDA",
                            Name = "Moldávia"
                        },
                        new
                        {
                            Id = 122,
                            Code = "MCO",
                            Name = "Mônaco"
                        },
                        new
                        {
                            Id = 123,
                            Code = "MNG",
                            Name = "Mongólia"
                        },
                        new
                        {
                            Id = 124,
                            Code = "MNE",
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 125,
                            Code = "MMR",
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 126,
                            Code = "NAM",
                            Name = "Namíbia"
                        },
                        new
                        {
                            Id = 127,
                            Code = "NRU",
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 128,
                            Code = "NPL",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 129,
                            Code = "NIC",
                            Name = "Nicarágua"
                        },
                        new
                        {
                            Id = 130,
                            Code = "NER",
                            Name = "Níger"
                        },
                        new
                        {
                            Id = 131,
                            Code = "NGA",
                            Name = "Nigéria"
                        },
                        new
                        {
                            Id = 132,
                            Code = "NOR",
                            Name = "Noruega"
                        },
                        new
                        {
                            Id = 133,
                            Code = "NZL",
                            Name = "Nova Zelândia"
                        },
                        new
                        {
                            Id = 134,
                            Code = "OMN",
                            Name = "Omã"
                        },
                        new
                        {
                            Id = 135,
                            Code = "NLD",
                            Name = "Países Baixos"
                        },
                        new
                        {
                            Id = 136,
                            Code = "PLW",
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 137,
                            Code = "PAN",
                            Name = "Panamá"
                        },
                        new
                        {
                            Id = 138,
                            Code = "PNG",
                            Name = "Papua-Nova Guiné"
                        },
                        new
                        {
                            Id = 139,
                            Code = "PAK",
                            Name = "Paquistão"
                        },
                        new
                        {
                            Id = 140,
                            Code = "PRY",
                            Name = "Paraguai"
                        },
                        new
                        {
                            Id = 141,
                            Code = "PER",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 142,
                            Code = "POL",
                            Name = "Polônia"
                        },
                        new
                        {
                            Id = 143,
                            Code = "PRT",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 144,
                            Code = "KEN",
                            Name = "Quênia"
                        },
                        new
                        {
                            Id = 145,
                            Code = "KGZ",
                            Name = "Quirguistão"
                        },
                        new
                        {
                            Id = 146,
                            Code = "GBR",
                            Name = "Reino Unido"
                        },
                        new
                        {
                            Id = 147,
                            Code = "CAF",
                            Name = "República Centro-Africana"
                        },
                        new
                        {
                            Id = 148,
                            Code = "COD",
                            Name = "República Democrática do Congo"
                        },
                        new
                        {
                            Id = 149,
                            Code = "DOM",
                            Name = "República Dominicana"
                        },
                        new
                        {
                            Id = 150,
                            Code = "CZE",
                            Name = "República Tcheca"
                        },
                        new
                        {
                            Id = 151,
                            Code = "ROU",
                            Name = "Romênia"
                        },
                        new
                        {
                            Id = 152,
                            Code = "RWA",
                            Name = "Ruanda"
                        },
                        new
                        {
                            Id = 153,
                            Code = "RUS",
                            Name = "Rússia"
                        },
                        new
                        {
                            Id = 154,
                            Code = "WSM",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 155,
                            Code = "SMR",
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 156,
                            Code = "LCA",
                            Name = "Santa Lúcia"
                        },
                        new
                        {
                            Id = 157,
                            Code = "KNA",
                            Name = "São Cristóvão e Névis"
                        },
                        new
                        {
                            Id = 158,
                            Code = "STP",
                            Name = "São Tomé e Príncipe"
                        },
                        new
                        {
                            Id = 159,
                            Code = "VCT",
                            Name = "São Vicente e Granadinas"
                        },
                        new
                        {
                            Id = 160,
                            Code = "SEN",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 161,
                            Code = "SLE",
                            Name = "Serra Leoa"
                        },
                        new
                        {
                            Id = 162,
                            Code = "SRB",
                            Name = "Sérvia"
                        },
                        new
                        {
                            Id = 163,
                            Code = "SYC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 164,
                            Code = "SGP",
                            Name = "Singapura"
                        },
                        new
                        {
                            Id = 165,
                            Code = "SYR",
                            Name = "Síria"
                        },
                        new
                        {
                            Id = 166,
                            Code = "SOM",
                            Name = "Somália"
                        },
                        new
                        {
                            Id = 167,
                            Code = "LKA",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 168,
                            Code = "SDN",
                            Name = "Sudão"
                        },
                        new
                        {
                            Id = 169,
                            Code = "SSD",
                            Name = "Sudão do Sul"
                        },
                        new
                        {
                            Id = 170,
                            Code = "SWE",
                            Name = "Suécia"
                        },
                        new
                        {
                            Id = 171,
                            Code = "CHE",
                            Name = "Suíça"
                        },
                        new
                        {
                            Id = 172,
                            Code = "SUR",
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 173,
                            Code = "THA",
                            Name = "Tailândia"
                        },
                        new
                        {
                            Id = 174,
                            Code = "TWN",
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = 175,
                            Code = "TJK",
                            Name = "Tajiquistão"
                        },
                        new
                        {
                            Id = 176,
                            Code = "TZA",
                            Name = "Tanzânia"
                        },
                        new
                        {
                            Id = 177,
                            Code = "TLS",
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = 178,
                            Code = "TGO",
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 179,
                            Code = "TON",
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 180,
                            Code = "TTO",
                            Name = "Trinidad e Tobago"
                        },
                        new
                        {
                            Id = 181,
                            Code = "TUN",
                            Name = "Tunísia"
                        },
                        new
                        {
                            Id = 182,
                            Code = "TKM",
                            Name = "Turcomenistão"
                        },
                        new
                        {
                            Id = 183,
                            Code = "TUR",
                            Name = "Turquia"
                        },
                        new
                        {
                            Id = 184,
                            Code = "TUV",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 185,
                            Code = "UKR",
                            Name = "Ucrânia"
                        },
                        new
                        {
                            Id = 186,
                            Code = "UGA",
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 187,
                            Code = "URY",
                            Name = "Uruguai"
                        },
                        new
                        {
                            Id = 188,
                            Code = "UZB",
                            Name = "Uzbequistão"
                        },
                        new
                        {
                            Id = 189,
                            Code = "VUT",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 190,
                            Code = "VAT",
                            Name = "Vaticano"
                        },
                        new
                        {
                            Id = 191,
                            Code = "VEN",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 192,
                            Code = "VNM",
                            Name = "Vietnã"
                        });
                });

            modelBuilder.Entity("Gaby.io.Models.GenreModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Gaby.io.Models.PublisherModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("Gaby.io.Models.ReadingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Month")
                        .HasColumnType("integer");

                    b.Property<int>("PagesRead")
                        .HasColumnType("integer");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId", "BookId", "Year", "Month");

                    b.ToTable("Readings");
                });

            modelBuilder.Entity("Gaby.io.Models.UserModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<string>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Gaby.io.Models.AuthorModel", b =>
                {
                    b.HasOne("Gaby.io.Models.CountryModel", "Country")
                        .WithMany("Authors")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Author_Country");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Gaby.io.Models.BookGenreModel", b =>
                {
                    b.HasOne("Gaby.io.Models.BookModel", "Book")
                        .WithMany("BookGenres")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BookGenre_Book");

                    b.HasOne("Gaby.io.Models.GenreModel", "Genre")
                        .WithMany("BookGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BookGenre_Genre");

                    b.Navigation("Book");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Gaby.io.Models.BookModel", b =>
                {
                    b.HasOne("Gaby.io.Models.AuthorModel", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Book_Author");

                    b.HasOne("Gaby.io.Models.PublisherModel", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Book_Publisher");

                    b.Navigation("Author");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Gaby.io.Models.ReadingModel", b =>
                {
                    b.HasOne("Gaby.io.Models.BookModel", "Book")
                        .WithMany("Readings")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Reading_Book");

                    b.HasOne("Gaby.io.Models.UserModel", "User")
                        .WithMany("Readings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Reading_User");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<string>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Gaby.io.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Gaby.io.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<string>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gaby.io.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Gaby.io.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gaby.io.Models.AuthorModel", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Gaby.io.Models.BookModel", b =>
                {
                    b.Navigation("BookGenres");

                    b.Navigation("Readings");
                });

            modelBuilder.Entity("Gaby.io.Models.CountryModel", b =>
                {
                    b.Navigation("Authors");
                });

            modelBuilder.Entity("Gaby.io.Models.GenreModel", b =>
                {
                    b.Navigation("BookGenres");
                });

            modelBuilder.Entity("Gaby.io.Models.PublisherModel", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Gaby.io.Models.UserModel", b =>
                {
                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
